---
- hosts: "*"
  remote_user: root
  tasks:
    - name: "Create a temporary file for our secret"
      tempfile:
          state: file
      register: secret_file
      notify:
          - delete secret file
    - name: "Populate the temporary file with the secret"
      copy:
          dest: "{{ secret_file.path }}"
          content: "{{ SECRET_VALUE }}"
    - name: "Get a list of the existing docker secrets"
      command: docker secret inspect
      register: docker_secrets
    - name: "Remove the docker secret, if it already exists"
      # TODO: ... tire fire
      command: docker secret rm "{{ docker_secrets.stdout.find_the_right_line.split()[0] }}"
      when: "{{ SECRET_KEY }} not in docker_secrets.stdout"
    - name: "Create the docker secret"
      command: docker secret create {{ SECRET_KEY }} {{ secret_file.path }}
  handlers:
      - name: delete secret file
        file:
            state: absent
            path: "{{ secret_file.path }}"
